name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CNAME: docusaurus-preview-test.hon.gy
    environment:
      name: github-pages
      url: ${{ github.ref == 'refs/heads/main' && steps.deployment.outputs.page_url || format('https://{0}.github.io/{1}/pr{2}', github.repository_owner, github.event.repository.name, github.event.pull_request.number) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          cd docs
          pnpm install --frozen-lockfile

      - name: Build website
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          cd docs
          pnpm build

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/build'

      - name: Deploy to GitHub Pages (main branch)
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          keep_files: true
          cname: ${{ env.CNAME }}

      - name: Deploy PR Preview
        if: github.event_name == 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          destination_dir: pr${{ github.event.pull_request.number }}
          keep_files: true
          cname: ${{ env.CNAME }}

      - name: Update PR Comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            📝 Documentation preview is ready!

            You can view the preview at: https://${{ env.CNAME }}/pr${{ github.event.pull_request.number }}/

            Note the original documentation is still available at: https://${{ env.CNAME }}/
